"""Plotting configurations.

"""


DEFAULT_CMAP = "plasma"

PHI1_C_ATTRACTOR_COLOR = 'blue'
PHI1_L_ATTRACTOR_COLOR = 'green'
PHI1_R_ATTRACTOR_COLOR = 'brown'
PHI1_SADDLE_COLOR = 'r'

PHI1_COLOR_DICT = {
    'saddle': PHI1_SADDLE_COLOR,
    'c': PHI1_C_ATTRACTOR_COLOR,
    'l': PHI1_L_ATTRACTOR_COLOR,
    'r': PHI1_R_ATTRACTOR_COLOR,
}

PHI2_C_ATTRACTOR_COLOR = 'brown'
PHI2_T_ATTRACTOR_COLOR = 'cyan'
PHI2_B_ATTRACTOR_COLOR = 'pink'
PHI2_M_ATTRACTOR_COLOR = 'grey'
PHI2_FLIP_CURVE_COLOR = 'purple'
PHI2_SADDLE_COLOR = 'r'

PHI2_COLOR_DICT = {
    'saddle': PHI2_SADDLE_COLOR,
    'c': PHI2_C_ATTRACTOR_COLOR,
    't': PHI2_T_ATTRACTOR_COLOR,
    'b': PHI2_B_ATTRACTOR_COLOR,
    'maximum': PHI2_M_ATTRACTOR_COLOR,
}